#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: fbbd4e3
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : ktexttemplate
Version  : 6.12.0
Release  : 18
URL      : https://download.kde.org/stable/frameworks/6.12/ktexttemplate-6.12.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.12/ktexttemplate-6.12.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.12/ktexttemplate-6.12.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause CC0-1.0 LGPL-2.0 LGPL-2.1
Requires: ktexttemplate-data = %{version}-%{release}
Requires: ktexttemplate-lib = %{version}-%{release}
Requires: ktexttemplate-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : mesa-dev
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The KTextTemplate Library
=========================
* About KTextTemplate
* Installation
* Licensing
* Contributing

%package data
Summary: data components for the ktexttemplate package.
Group: Data

%description data
data components for the ktexttemplate package.


%package dev
Summary: dev components for the ktexttemplate package.
Group: Development
Requires: ktexttemplate-lib = %{version}-%{release}
Requires: ktexttemplate-data = %{version}-%{release}
Provides: ktexttemplate-devel = %{version}-%{release}
Requires: ktexttemplate = %{version}-%{release}

%description dev
dev components for the ktexttemplate package.


%package lib
Summary: lib components for the ktexttemplate package.
Group: Libraries
Requires: ktexttemplate-data = %{version}-%{release}
Requires: ktexttemplate-license = %{version}-%{release}

%description lib
lib components for the ktexttemplate package.


%package license
Summary: license components for the ktexttemplate package.
Group: Default

%description license
license components for the ktexttemplate package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n ktexttemplate-6.12.0
cd %{_builddir}/ktexttemplate-6.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742417417
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1742417417
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktexttemplate
cp %{_builddir}/ktexttemplate-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/ktexttemplate/07c1ab270255cf247438e2358ff0c18835b6a6ce || :
cp %{_builddir}/ktexttemplate-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/ktexttemplate/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/ktexttemplate-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/ktexttemplate/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/ktexttemplate-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/ktexttemplate/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories6/ktexttemplate.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/KTextTemplate/KTextTemplate/AbstractLocalizer
/usr/include/KF6/KTextTemplate/KTextTemplate/AbstractNodeFactory
/usr/include/KF6/KTextTemplate/KTextTemplate/AbstractTemplateLoader
/usr/include/KF6/KTextTemplate/KTextTemplate/CachingLoaderDecorator
/usr/include/KF6/KTextTemplate/KTextTemplate/Context
/usr/include/KF6/KTextTemplate/KTextTemplate/Engine
/usr/include/KF6/KTextTemplate/KTextTemplate/Exception
/usr/include/KF6/KTextTemplate/KTextTemplate/FileSystemTemplateLoader
/usr/include/KF6/KTextTemplate/KTextTemplate/Filter
/usr/include/KF6/KTextTemplate/KTextTemplate/FilterExpression
/usr/include/KF6/KTextTemplate/KTextTemplate/InMemoryTemplateLoader
/usr/include/KF6/KTextTemplate/KTextTemplate/MetaType
/usr/include/KF6/KTextTemplate/KTextTemplate/Node
/usr/include/KF6/KTextTemplate/KTextTemplate/NodeList
/usr/include/KF6/KTextTemplate/KTextTemplate/OutputStream
/usr/include/KF6/KTextTemplate/KTextTemplate/Parser
/usr/include/KF6/KTextTemplate/KTextTemplate/QtLocalizer
/usr/include/KF6/KTextTemplate/KTextTemplate/RenderContext
/usr/include/KF6/KTextTemplate/KTextTemplate/SafeString
/usr/include/KF6/KTextTemplate/KTextTemplate/TagLibraryInterface
/usr/include/KF6/KTextTemplate/KTextTemplate/Template
/usr/include/KF6/KTextTemplate/KTextTemplate/TemplateLoader
/usr/include/KF6/KTextTemplate/KTextTemplate/Token
/usr/include/KF6/KTextTemplate/KTextTemplate/TypeAccessor
/usr/include/KF6/KTextTemplate/KTextTemplate/Util
/usr/include/KF6/KTextTemplate/KTextTemplate/Variable
/usr/include/KF6/KTextTemplate/ktexttemplate/abstractlocalizer.h
/usr/include/KF6/KTextTemplate/ktexttemplate/cachingloaderdecorator.h
/usr/include/KF6/KTextTemplate/ktexttemplate/context.h
/usr/include/KF6/KTextTemplate/ktexttemplate/engine.h
/usr/include/KF6/KTextTemplate/ktexttemplate/exception.h
/usr/include/KF6/KTextTemplate/ktexttemplate/filter.h
/usr/include/KF6/KTextTemplate/ktexttemplate/filterexpression.h
/usr/include/KF6/KTextTemplate/ktexttemplate/ktexttemplate_export.h
/usr/include/KF6/KTextTemplate/ktexttemplate/metatype.h
/usr/include/KF6/KTextTemplate/ktexttemplate/node.h
/usr/include/KF6/KTextTemplate/ktexttemplate/outputstream.h
/usr/include/KF6/KTextTemplate/ktexttemplate/parser.h
/usr/include/KF6/KTextTemplate/ktexttemplate/qtlocalizer.h
/usr/include/KF6/KTextTemplate/ktexttemplate/rendercontext.h
/usr/include/KF6/KTextTemplate/ktexttemplate/safestring.h
/usr/include/KF6/KTextTemplate/ktexttemplate/taglibraryinterface.h
/usr/include/KF6/KTextTemplate/ktexttemplate/template.h
/usr/include/KF6/KTextTemplate/ktexttemplate/templateloader.h
/usr/include/KF6/KTextTemplate/ktexttemplate/token.h
/usr/include/KF6/KTextTemplate/ktexttemplate/typeaccessor.h
/usr/include/KF6/KTextTemplate/ktexttemplate/util.h
/usr/include/KF6/KTextTemplate/ktexttemplate/variable.h
/usr/include/KF6/KTextTemplate/ktexttemplate_version.h
/usr/lib64/cmake/KF6TextTemplate/KF6TextTemplateConfig.cmake
/usr/lib64/cmake/KF6TextTemplate/KF6TextTemplateConfigVersion.cmake
/usr/lib64/cmake/KF6TextTemplate/KF6TextTemplateMacros.cmake
/usr/lib64/cmake/KF6TextTemplate/KF6TextTemplateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6TextTemplate/KF6TextTemplateTargets.cmake
/usr/lib64/libKF6TextTemplate.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF6TextTemplate.so.6
/usr/lib64/libKF6TextTemplate.so.6.12.0
/usr/lib64/qt6/plugins/kf6/ktexttemplate/ktexttemplate_defaultfilters.so
/usr/lib64/qt6/plugins/kf6/ktexttemplate/ktexttemplate_defaulttags.so
/usr/lib64/qt6/plugins/kf6/ktexttemplate/ktexttemplate_i18ntags.so
/usr/lib64/qt6/plugins/kf6/ktexttemplate/ktexttemplate_loadertags.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktexttemplate/07c1ab270255cf247438e2358ff0c18835b6a6ce
/usr/share/package-licenses/ktexttemplate/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/ktexttemplate/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/ktexttemplate/a4c60b3fefda228cd7439d3565df043192fef137
